
package com.segurosbolivar.mensajeria.serviciosws;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6hudson-86 
 * Generated source version: 2.2
 * 
 */
public interface SolicitudesServicesAsyncHandler {


}
