
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.borrar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BorrarDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/eliminar/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BorrarDocumentoService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.segurosbolivar.services.filenet.eliminar.OpBorrarDocumentoResponse
     */
    @WebMethod(action = "http://localhost:9080/services/FilenetWS/opBorrarDocumento")
    @WebResult(name = "opBorrarDocumentoResponse", targetNamespace = "http://services.segurosbolivar.com/fileNet/eliminar/", partName = "parameters")
    public OpBorrarDocumentoResponse opBorrarDocumento(
        @WebParam(name = "BorrarDocumento", targetNamespace = "http://services.segurosbolivar.com/fileNet/eliminar/", partName = "parameters")
        BorrarDocumento parameters);

}
