package com.segurosbolivar.avaluos.modelo.ws.service.correo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.segurosbolivar.avaluos.modelo.ws.service.correo.RespuestaSolicitudDTO;
import com.segurosbolivar.avaluos.modelo.ws.service.correo.RtaConsultarSolicitudDTO;
import com.segurosbolivar.avaluos.modelo.ws.service.correo.SolicitudDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6hudson-86 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SolicitudesServices", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com")
@XmlSeeAlso({
	com.segurosbolivar.avaluos.modelo.ws.service.correo.ObjectFactory.class,
	com.segurosbolivar.avaluos.modelo.ws.service.correo.ObjectFactory.class
})
public interface SolicitudesServices {


    /**
     * 
     * @param datosSolicitud
     * @return
     *     returns com.segurosbolivar.mensajeria.utilsws.RespuestaSolicitudDTO
     */
    @WebMethod
    @WebResult(name = "recibirSolicitudWSReturn", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com")
    @RequestWrapper(localName = "recibirSolicitudWS", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com", className = "com.segurosbolivar.mensajeria.serviciosws.RecibirSolicitudWS")
    @ResponseWrapper(localName = "recibirSolicitudWSResponse", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com", className = "com.segurosbolivar.mensajeria.serviciosws.RecibirSolicitudWSResponse")
    public RespuestaSolicitudDTO recibirSolicitudWS(
        @WebParam(name = "datosSolicitud", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com")
        SolicitudDTO datosSolicitud);

    /**
     * 
     * @param numSolicitud
     * @param codAplicacion
     * @return
     *     returns com.segurosbolivar.mensajeria.utilsws.RtaConsultarSolicitudDTO
     */
    @WebMethod
    @WebResult(name = "consultarSolicitudWSReturn", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com")
    @RequestWrapper(localName = "consultarSolicitudWS", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com", className = "com.segurosbolivar.mensajeria.serviciosws.ConsultarSolicitudWS")
    @ResponseWrapper(localName = "consultarSolicitudWSResponse", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com", className = "com.segurosbolivar.mensajeria.serviciosws.ConsultarSolicitudWSResponse")
    public RtaConsultarSolicitudDTO consultarSolicitudWS(
        @WebParam(name = "numSolicitud", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com")
        long numSolicitud,
        @WebParam(name = "codAplicacion", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com")
        String codAplicacion);

}