package com.segurosbolivar.avaluos.modelo.ws.service.correo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6hudson-86 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitudesServicesService", targetNamespace = "http://serviciosws.mensajeria.segurosbolivar.com", wsdlLocation = "https://ambientepruebas.segurosbolivar.com/MensajeriaBolivarWS/services/SolicitudesServices?WSDL")
public class SolicitudesServicesService
    extends Service
{

    private final static URL SOLICITUDESSERVICESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.segurosbolivar.avaluos.modelo.ws.service.correo.SolicitudesServicesService.class.getName());
    private final static QName SOLICITUDESSERVICESSERVICE_QNAME = new QName("http://serviciosws.mensajeria.segurosbolivar.com", "SolicitudesServicesService");

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.segurosbolivar.avaluos.modelo.ws.service.correo.SolicitudesServicesService.class.getResource(".");
            url = new URL(baseUrl, "https://ambientepruebas.segurosbolivar.com/MensajeriaBolivarWS/services/SolicitudesServices?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://ambientepruebas.segurosbolivar.com/MensajeriaBolivarWS/services/SolicitudesServices?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SOLICITUDESSERVICESSERVICE_WSDL_LOCATION = url;
    }

    public SolicitudesServicesService() {
        super(SOLICITUDESSERVICESSERVICE_WSDL_LOCATION, SOLICITUDESSERVICESSERVICE_QNAME);
    }

    public SolicitudesServicesService(WebServiceFeature... features) {
        super(SOLICITUDESSERVICESSERVICE_WSDL_LOCATION, SOLICITUDESSERVICESSERVICE_QNAME, features);
    }

    public SolicitudesServicesService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITUDESSERVICESSERVICE_QNAME);
    }

    public SolicitudesServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOLICITUDESSERVICESSERVICE_QNAME, features);
    }

    public SolicitudesServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolicitudesServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SolicitudesServices
     */
    @WebEndpoint(name = "SolicitudesServices")
    public SolicitudesServices getSolicitudesServices() {
        return super.getPort(new QName("http://serviciosws.mensajeria.segurosbolivar.com", "SolicitudesServices"), SolicitudesServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitudesServices
     */
    @WebEndpoint(name = "SolicitudesServices")
    public SolicitudesServices getSolicitudesServices(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviciosws.mensajeria.segurosbolivar.com", "SolicitudesServices"), SolicitudesServices.class, features);
    }

}