
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.modificar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModificarDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/modificar/", wsdlLocation = "https://ambientepruebas.segurosbolivar.com/SBServicioFilenetSOAP/ModificarDocumentoService/WEB-INF/wsdl/ModificarDocumentoService.wsdl")
public class ModificarDocumentoService_Service
    extends Service
{

    private final static URL MODIFICARDOCUMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFICARDOCUMENTOSERVICE_EXCEPTION;
    private final static QName MODIFICARDOCUMENTOSERVICE_QNAME = new QName("http://services.segurosbolivar.com/fileNet/modificar/", "ModificarDocumentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ambientepruebas.segurosbolivar.com/SBServicioFilenetSOAP/ModificarDocumentoService/WEB-INF/wsdl/ModificarDocumentoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODIFICARDOCUMENTOSERVICE_WSDL_LOCATION = url;
        MODIFICARDOCUMENTOSERVICE_EXCEPTION = e;
    }

    public ModificarDocumentoService_Service() {
        super(__getWsdlLocation(), MODIFICARDOCUMENTOSERVICE_QNAME);
    }

    public ModificarDocumentoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFICARDOCUMENTOSERVICE_QNAME, features);
    }

    public ModificarDocumentoService_Service(URL wsdlLocation) {
        super(wsdlLocation, MODIFICARDOCUMENTOSERVICE_QNAME);
    }

    public ModificarDocumentoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFICARDOCUMENTOSERVICE_QNAME, features);
    }

    public ModificarDocumentoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModificarDocumentoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModificarDocumentoService
     */
    @WebEndpoint(name = "ModificarDocumentoWSSOAP")
    public ModificarDocumentoService getModificarDocumentoWSSOAP() {
        return super.getPort(new QName("http://services.segurosbolivar.com/fileNet/modificar/", "ModificarDocumentoWSSOAP"), ModificarDocumentoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModificarDocumentoService
     */
    @WebEndpoint(name = "ModificarDocumentoWSSOAP")
    public ModificarDocumentoService getModificarDocumentoWSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.segurosbolivar.com/fileNet/modificar/", "ModificarDocumentoWSSOAP"), ModificarDocumentoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFICARDOCUMENTOSERVICE_EXCEPTION!= null) {
            throw MODIFICARDOCUMENTOSERVICE_EXCEPTION;
        }
        return MODIFICARDOCUMENTOSERVICE_WSDL_LOCATION;
    }

}
