
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.modificar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModificarDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/modificar/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModificarDocumentoService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.segurosbolivar.services.filenet.modificar.OpModificarDocumentoResponse
     */
    @WebMethod(action = "http://localhost:9080/services/FilenetWS/opModificarDocumento")
    @WebResult(name = "opModificarDocumentoResponse", targetNamespace = "http://services.segurosbolivar.com/fileNet/modificar/", partName = "parameters")
    public OpModificarDocumentoResponse opModificarDocumento(
        @WebParam(name = "nuevoDocumento", targetNamespace = "http://services.segurosbolivar.com/fileNet/modificar/", partName = "parameters")
        NuevoDocumento parameters);

}
