
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.consultaringresar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IngresaConsultaDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/cargar/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IngresaConsultaDocumentoService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.consultaringresar.OpIngresaConsultaDocumentoResponse
     * @throws IngresaConsultaDocumentoFaultMsg
     */
    @WebMethod(action = "http://localhost:9080/services/FilenetWS/opIngresaConsultaDocumento")
    @WebResult(name = "opIngresaConsultaDocumentoResponse", targetNamespace = "http://services.segurosbolivar.com/fileNet/cargar/", partName = "parameters")
    public OpIngresaConsultaDocumentoResponse opIngresaConsultaDocumento(
        @WebParam(name = "listaDocumento", targetNamespace = "http://services.segurosbolivar.com/fileNet/cargar/", partName = "parameters")
        ListaDocumento parameters)
        throws IngresaConsultaDocumentoFaultMsg
    ;

}
