
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.obtener;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ObtenerDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/obtener/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ObtenerDocumentoService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.segurosbolivar.services.filenet.obtener.OpObtenerDocumentoResponse
     */
    @WebMethod(action = "http://localhost:9080/services/FilenetWS/opObtenerDocumento")
    @WebResult(name = "opObtenerDocumentoResponse", targetNamespace = "http://services.segurosbolivar.com/fileNet/obtener/", partName = "parameters")
    public OpObtenerDocumentoResponse opObtenerDocumento(
        @WebParam(name = "ObtenerDocumento", targetNamespace = "http://services.segurosbolivar.com/fileNet/obtener/", partName = "parameters")
        ObtenerDocumento parameters);

}
