
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.ingresar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "opIngresarDocumentoFault", targetNamespace = "http://services.segurosbolivar.com/fileNet/cargar/")
public class IngresarDocumentoFaultMsg
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OpIngresarDocumentoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IngresarDocumentoFaultMsg(String message, OpIngresarDocumentoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IngresarDocumentoFaultMsg(String message, OpIngresarDocumentoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.segurosbolivar.services.filenet.cargar.OpIngresarDocumentoFault
     */
    public OpIngresarDocumentoFault getFaultInfo() {
        return faultInfo;
    }

}
