
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.ingresar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IngresarDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/cargar/", wsdlLocation = "https://ambientepruebas.segurosbolivar.com/SBServicioFilenetSOAP/IngresarDocumentoService/WEB-INF/wsdl/IngresarDocumentoService.wsdl")
public class IngresarDocumentoService_Service
    extends Service
{

    private final static URL INGRESARDOCUMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INGRESARDOCUMENTOSERVICE_EXCEPTION;
    private final static QName INGRESARDOCUMENTOSERVICE_QNAME = new QName("http://services.segurosbolivar.com/fileNet/cargar/", "IngresarDocumentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ambientepruebas.segurosbolivar.com/SBServicioFilenetSOAP/IngresarDocumentoService/WEB-INF/wsdl/IngresarDocumentoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INGRESARDOCUMENTOSERVICE_WSDL_LOCATION = url;
        INGRESARDOCUMENTOSERVICE_EXCEPTION = e;
    }

    public IngresarDocumentoService_Service() {
        super(__getWsdlLocation(), INGRESARDOCUMENTOSERVICE_QNAME);
    }

    public IngresarDocumentoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INGRESARDOCUMENTOSERVICE_QNAME, features);
    }

    public IngresarDocumentoService_Service(URL wsdlLocation) {
        super(wsdlLocation, INGRESARDOCUMENTOSERVICE_QNAME);
    }

    public IngresarDocumentoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INGRESARDOCUMENTOSERVICE_QNAME, features);
    }

    public IngresarDocumentoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IngresarDocumentoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IngresarDocumentoService
     */
    @WebEndpoint(name = "IngresarDocumentoWSSOAP")
    public IngresarDocumentoService getIngresarDocumentoWSSOAP() {
        return super.getPort(new QName("http://services.segurosbolivar.com/fileNet/cargar/", "IngresarDocumentoWSSOAP"), IngresarDocumentoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IngresarDocumentoService
     */
    @WebEndpoint(name = "IngresarDocumentoWSSOAP")
    public IngresarDocumentoService getIngresarDocumentoWSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.segurosbolivar.com/fileNet/cargar/", "IngresarDocumentoWSSOAP"), IngresarDocumentoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INGRESARDOCUMENTOSERVICE_EXCEPTION!= null) {
            throw INGRESARDOCUMENTOSERVICE_EXCEPTION;
        }
        return INGRESARDOCUMENTOSERVICE_WSDL_LOCATION;
    }

}
