
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.consultar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/consultar/", wsdlLocation = "https://ambientepruebas.segurosbolivar.com/SBServicioFilenetSOAP/ConsultarDocumentoService/WEB-INF/wsdl/ConsultarDocumentoService.wsdl")
public class ConsultarDocumentoService_Service
    extends Service
{

    private final static URL CONSULTARDOCUMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTARDOCUMENTOSERVICE_EXCEPTION;
    private final static QName CONSULTARDOCUMENTOSERVICE_QNAME = new QName("http://services.segurosbolivar.com/fileNet/consultar/", "ConsultarDocumentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ambientepruebas.segurosbolivar.com/SBServicioFilenetSOAP/ConsultarDocumentoService/WEB-INF/wsdl/ConsultarDocumentoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARDOCUMENTOSERVICE_WSDL_LOCATION = url;
        CONSULTARDOCUMENTOSERVICE_EXCEPTION = e;
    }

    public ConsultarDocumentoService_Service() {
        super(__getWsdlLocation(), CONSULTARDOCUMENTOSERVICE_QNAME);
    }

    public ConsultarDocumentoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARDOCUMENTOSERVICE_QNAME, features);
    }

    public ConsultarDocumentoService_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARDOCUMENTOSERVICE_QNAME);
    }

    public ConsultarDocumentoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARDOCUMENTOSERVICE_QNAME, features);
    }

    public ConsultarDocumentoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarDocumentoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarDocumentoService
     */
    @WebEndpoint(name = "ConsultarDocumentoWSSOAP")
    public ConsultarDocumentoService getConsultarDocumentoWSSOAP() {
        return super.getPort(new QName("http://services.segurosbolivar.com/fileNet/consultar/", "ConsultarDocumentoWSSOAP"), ConsultarDocumentoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarDocumentoService
     */
    @WebEndpoint(name = "ConsultarDocumentoWSSOAP")
    public ConsultarDocumentoService getConsultarDocumentoWSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.segurosbolivar.com/fileNet/consultar/", "ConsultarDocumentoWSSOAP"), ConsultarDocumentoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARDOCUMENTOSERVICE_EXCEPTION!= null) {
            throw CONSULTARDOCUMENTOSERVICE_EXCEPTION;
        }
        return CONSULTARDOCUMENTOSERVICE_WSDL_LOCATION;
    }

}
