
package com.segurosbolivar.avaluos.modelo.ws.clientes.filenet.consultar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarDocumentoService", targetNamespace = "http://services.segurosbolivar.com/fileNet/consultar/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarDocumentoService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.segurosbolivar.services.filenet.consultar.OpConsultarDocumentoResponse
     */
    @WebMethod(action = "http://localhost:9080/services/FilenetWS/opConsultarDocumento")
    @WebResult(name = "opConsultarDocumentoResponse", targetNamespace = "http://services.segurosbolivar.com/fileNet/consultar/", partName = "parameters")
    public OpConsultarDocumentoResponse opConsultarDocumento(
        @WebParam(name = "filtroDocumentos", targetNamespace = "http://services.segurosbolivar.com/fileNet/consultar/", partName = "parameters")
        FiltroDocumentos parameters);

}
